your_contacts/contacts_book/urls.py
from django.urls import path
from . import views

app_name = 'contacts_book'

urlpatterns = [
    path('view_contacts/', views.ViewContacts_view.as_view(), name='view_contacts'),
    
]

your_contacts/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register_user/', views.register_user_view, name='register_user'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

your_contacts/your_contacts/urls.py
from django.contrib import admin
from django.urls import path, include
from contacts_book import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('user_contacts/', views.user_contacts, name='contacts'),
    path('users/', include('users.urls')),

]

your_contacts/contacts_book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Contacts_list(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
class Contact(models.Model):
    contacts_list = models.ForeignKey(Contacts_list,on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    address = models.TextField(max_length=300, blank=True)
    telephone_number = models.CharField(max_length=50, blank=True)
    email = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.name

# Create a contact list when the user is created
@receiver(post_save, sender=User)
def create_user_contacts_list(sender, instance, created, **kwargs):
    if created:
        Contacts_list.objects.create(user=instance)

#Update contacts list when user is updated
@receiver(post_save, sender=User)
def save_user_contact_list(sender, instance, **kwargs):
    instance.contacts_list.save()

your_contacts/users/models.py
from django.db import models

# Create your models here.

your_contacts/contacts_book/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


from . import models

# Create your views here.
def home(request):
    return render(request, 'home.html')

class ViewContacts_view(LoginRequiredMixin, ListView):
    context_object_name = 'contacts_list' 
    model = models.Contact
    template_name = 'contacts_book/view_all_contacts.html'
    paginate_by = 5
    
    def get_queryset(self):
        # Get the Contacts_list instance for the current user
        c_list = models.Contacts_list.objects.get(user=self.request.user)
        # Filter contacts by the retrieved Contacts_list instance
        queryset = models.Contact.objects.filter(contacts_list=c_list)
        return queryset

your_contacts/users/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.
def register_user_view(request):
    registered = False
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True
            return render(request, "users/register_user.html", {'registered' : registered})
    else:
        form = UserCreationForm()

    return render(request, 'users/register_user.html', {"form": form, 'registered' : registered})

def login_view(request): 
    logged_in =False
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            logged_in = True
            return render(request, "users/login.html", {"logged_in": logged_in})
    else:
        form = AuthenticationForm()

    return render(request, 'users/login.html', {"form": form, "logged_in": logged_in})

def logout_view(request):
    was_logged_in = False
    if request.method == 'POST' and request.user.is_authenticated:
        logout(request)
        was_logged_in = True

    return render(request, "users/logout.html", {"was_logged_in": was_logged_in})

        

your_contacts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contacts App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href = {% static 'css/style.css' %}
</head>
<body>
    <!-- Side menu -->
    <div class="container-fluid">
        <div class="row content">
          <div class="col-sm-3 sidenav">
            <h4>Contacts App</h4>
            <ul class="nav nav-pills flex-column ">
              <li><a href="{% url 'home' %}">Home</a></li>
              {% if request.user.is_authenticated %}
                <li><a href="{% url 'contacts_book:view_contacts' %}">Contacts</a></li>  
                <li><a href="{% url 'users:logout' %}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'users:login' %}">Login</a></li>
                <li><a href="{% url 'users:register_user' %}">Sign up</a></li>                            
              {% endif %}
            </ul><br>
          </div>
          <div class="col-sm-9">
          {% block page_contents %}

          {% endblock %}
          </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

your_contacts/templates/contacts_book/view_all_contacts.html
{% extends "base.html" %}
{% block page_contents %}
    <ol>
        {% for contact in contacts_list %}
            <li>Name: {{ contact.name }}</li>
            <ul>
                <li>Address: {{ contact.address }}</li>
                <li>Tel: {{ contact.telephone_number }}</li>
                <li>Email: {{ contact.email }}</li>
            </ul>
            <br>
        {% endfor %}
    </ol>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

your_contacts/templates/home.html
{% extends "base.html" %}
{% block page_contents %}

   <h1>Welcome to the "Contacts" online app</h1>
   <h2>Create a list of contacts for free</h2>
   <p>If you already have an accout, please <a href="{% url 'users:login' %}">login</a> to view your contacts.</p>
   <p>If you don't have an accout, please feel free to <a href="{% url 'users:login' %}">sign up</a> for a free account.</p>
   

{% endblock %}

your_contacts/templates/user_contacts.html
{% extends "base.html" %}
{% block page_contents %}
    <h1>Contacts page</h1>
    <p>From here, the user can CURD and search for contacts.</p>
{% endblock %}

your_contacts/templates/users/login.html
{% extends "base.html" %}
{% block page_contents %}
    {% if logged_in %}
        <h1>Thank you. You are logged in.</h1>
        <h2>Please go to contacts screen to view your contacts.</h2>
    {% else %}
        <h1>User Login form</h1>
        <form action="/users/login/" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="login">
        </form>
    {% endif %}
{% endblock %}

your_contacts/templates/users/logout.html
{% extends "base.html" %}
{% block page_contents %}
    {% if was_logged_in %}
        <h1>You are now logged out.</h1>
        <h2>See you back soon!</h2>
    {% else %}
        {% if request.user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Logout">
            </form>
        {% else %}
            <h1>You were not logged in.</h1>
            <h2>If you want to use this app, please register or log in with a valid user name!</h2>
        {% endif %}    
    {% endif %}
{% endblock %}

your_contacts/templates/users/register_user.html
{% extends "base.html" %}
{% block page_contents %}
    {% if registered %}
        <h1>Thank you for registering.</h1>
        <h2>Please login to start adding your contacts.</h2>
    {% else %}
        <h1>Uer Registration</h1>
        <form action="/users/register_user/" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
{% endblock %}